In [1]:
import pandas as pd
import requests
import re
import numpy as np
import ast
import pickle

In [2]:
# new_df = pd.read_csv('IMDB-Movie-Dataset(2023-1951).csv',index_col=0)
# new_df2=pd.read_csv('Processed_2024_updated.csv',index_col=0)

In [3]:
new_df = pd.read_csv("final_movie_dataset_with_keyword.csv", index_col=0)

In [4]:
new_df.sample(5)

movie_id       movie_name    year                 genre  \
2831  tt32106143  Love Mocktail 2  2024.0        Drama, Romance   
439    tt0278291          Ajnabee    2001  Action, Crime, Drama   
3607  tt33396044      The E-Ghost  2024.0                Horror   
1554   tt1027813       Free Entry    2006        Drama, Romance   
3131  tt30139449         The Suit  2024.0               unknown   

                                               overview  \
2831  A sequel to Love Mocktail. Revolves around Aad...   
439   A newlywed couple, Raj and Priya, move to Swit...   
3607                                            Unknown   
1554  The movie is a story of twin sisters coveting ...   
3131                                            Unknown   

                                               director  \
2831                                    Darling Krishna   
439   Abbas Alibhai Burmawalla, Mastan Alibhai Burma...   
3607                                      Ankush Darode   
1554                                         Kanti Shah   
3131                                      S. Bhagat Raj   

                                                   cast  movie_id2  \
2831  Baby Aaradhya, Abhilaash, Khushi Achar, Baby A...   32106143   
439   Akshay Kumar, Bobby Deol, Kareena Kapoor, Bipa...     278291   
3607  Chirag Jani, Sameer Khan, Ayesha Khana, Pramod...   33396044   
1554            Anil Nagrath, Amit Pachori, Sapna Sappu    1027813   
3131  Sujay Arya, Umesh Banakar, Guruprasad, Kamal, ...   30139449   

                                               Keywords  
2831                                                NaN  
439   visual impairment, latex, blood, woman wrapped...  
3607                                                NaN  
1554                                                NaN  
3131                                                NaN

In [5]:
new_df.shape

(4031, 9)

In [6]:
new_df["movie_id"].duplicated().sum()

55

In [7]:
new_df = new_df.drop_duplicates(subset='movie_id', keep='first')

In [8]:
new_df["movie_id"].duplicated().sum()

0

In [9]:
new_df.isnull().sum()

movie_id         0
movie_name       0
year            65
genre            0
overview         0
director         0
cast             0
movie_id2        0
Keywords      1746
dtype: int64

In [10]:
new_df["year"]= new_df["year"].replace(np.nan, "Unknown")
new_df["Keywords"]= new_df["Keywords"].replace(np.nan, "Unknown")

In [11]:
new_df.isnull().sum()

movie_id      0
movie_name    0
year          0
genre         0
overview      0
director      0
cast          0
movie_id2     0
Keywords      0
dtype: int64

In [12]:
new_df['year'].unique()

array(['2023', '2016', '2009', '2012', '2001', '2007', '2018', '2022',
       '1982', '2014', '2010', '2017', '2015', '2024', '2004', '2011',
       '1998', '2006', '2002', '2019', '2013', '2003', '2021', '1999',
       '1995', '2008', '2020', '2000', '1975', 'Unknown', '1993', '1994',
       '2025', '2005', '1997', '1967', '1992', 'XV2016', '1991', '1965',
       '1988', '1970', '1957', '1956', '1990', 'V2020', '1983', '1996',
       '1987', '1959', 'X2020', '1981', '1978', '1989', 'V', '1972',
       '1960', '1953', '1973', '1966', '1955', '1984', '1964', '1962',
       '1977', '1971', '1985', '1980', '2026', '1976', '1958', '1986',
       'X', '1974', '1932', '1969', '1979', '1961', '1968', 'V2023',
       '1951', '1954', 'XXX', 'XXV', '1963', '2024.0'], dtype=object)

In [13]:
new_df['year'].value_counts().sum()

3976

In [14]:
def remove_alpha_or_nan(year):
    # Use regular expression to remove all alphabetic characters
    cleaned_year = re.sub(r'[A-Za-z]', '', year)
    
    # If the result is an empty string, return NaN
    if cleaned_year == '':
        return 0
    return cleaned_year

In [15]:
new_df['year'] = new_df['year'].astype(str).apply(remove_alpha_or_nan)

In [16]:
new_df['year'].unique()

array(['2023', '2016', '2009', '2012', '2001', '2007', '2018', '2022',
       '1982', '2014', '2010', '2017', '2015', '2024', '2004', '2011',
       '1998', '2006', '2002', '2019', '2013', '2003', '2021', '1999',
       '1995', '2008', '2020', '2000', '1975', 0, '1993', '1994', '2025',
       '2005', '1997', '1967', '1992', '1991', '1965', '1988', '1970',
       '1957', '1956', '1990', '1983', '1996', '1987', '1959', '1981',
       '1978', '1989', '1972', '1960', '1953', '1973', '1966', '1955',
       '1984', '1964', '1962', '1977', '1971', '1985', '1980', '2026',
       '1976', '1958', '1986', '1974', '1932', '1969', '1979', '1961',
       '1968', '1951', '1954', '1963', '2024.0'], dtype=object)

In [17]:
new_df['year'].values

array(['2023', '2023', '2023', ..., '2024.0', '2024.0', '2024.0'],
      dtype=object)

In [18]:
new_df['year'] = new_df['year'].astype(float)

In [19]:
new_df['year'] = new_df['year'].astype(int)

In [20]:
new_df.dtypes

movie_id      object
movie_name    object
year           int32
genre         object
overview      object
director      object
cast          object
movie_id2      int64
Keywords      object
dtype: object

In [21]:
new_df['cast'] = new_df['cast'].str.replace(' ', '')
new_df['genre'] = new_df['genre'].str.replace(' ', '')
new_df['director'] = new_df['director'].str.replace(' ', '')
new_df['Keywords'] = new_df['Keywords'].str.replace(' ', '')

In [22]:
new_df['overview'] = new_df['overview'].apply(lambda x:x.split())
new_df['overview']

0       [A, high-octane, action, thriller, which, outl...
1       [A, single, mother, and, her, daughter, who, c...
2       [A, retired, jailer, goes, on, a, manhunt, to,...
3       [Flamboyant, Punjabi, Rocky, and, intellectual...
4       [An, unhappy, civilian, asks, the, court, to, ...
                              ...                        
4026    [A, young, worker's, epic, bicycle, journey, h...
4027                                            [Unknown]
4028                                            [Unknown]
4029    ['Satchi, Perumal', with, the, main, lead, Per...
4030    [This, is, a, story, of, a, young, man, boy, n...
Name: overview, Length: 3976, dtype: object

In [23]:
new_df['genre'] = new_df['genre'].apply(lambda x:x.split())
new_df['director'] = new_df['director'].apply(lambda x:x.split())
new_df['cast'] = new_df['cast'].apply(lambda x:x.split())
new_df['Keywords'] = new_df['Keywords'].apply(lambda x:x.split())

In [24]:
new_df.sample(5)

movie_id                 movie_name  year                   genre  \
1621   tt7972000                      Junko  2017                 [Crime]   
3065  tt31957391         Krime Komedy Karma  2024                [Comedy]   
115   tt23554840            The Vaccine War  2023        [Drama,Thriller]   
3588  tt30612316           In Your Language  2024           [Documentary]   
891    tt0095198  Gangaa Jamunaa Saraswathi  1988  [Action,Drama,Romance]   

                                               overview              director  \
1621                                     [Add, a, Plot]       [AbhinavThakur]   
3065                                          [Unknown]     [PrabhatSachdeva]   
115   [Based, on, India's, battle, against, Covid-19...      [VivekAgnihotri]   
3588  [A, group, of, students, aged, between, 18, to...  [RamGayathriKrishna]   
891   [Gangaa, Jamunaa, and, Saraswathi, the, most, ...       [ManmohanDesai]   

                                                   cast  movie_id2  \
1621  [NeelamDeysarkar,AayushThakur,AaravMavi,Aashif...    7972000   
3065  [AishwaryaRajBhakuni,PreetBhatti,K.P.Maurya,Fa...   31957391   
115   [NiveditaBhattacharya,AnupamKher,GirijaOak,Nan...   23554840   
3588                                [MaitreyaMaitreyan]   30612316   
891   [AmitabhBachchan,MithunChakraborty,JayaPrada,M...      95198   

                                               Keywords  
1621                                          [Unknown]  
3065                                          [Unknown]  
115   [hospital,doctor,pandemic,medicaldrama,coronav...  
3588                                          [Unknown]  
891   [unclenephewrelationship,watertower,amnesia,fi...

In [25]:
new_df['tags'] = new_df['overview'] + new_df['genre'] + new_df['director'] + new_df['cast'] + new_df["Keywords"]

In [26]:
new_df = new_df.drop(columns=['overview','genre','cast','director', 'Keywords'])

In [27]:
new_df.head()

movie_id                       movie_name  year  movie_id2  \
0  tt15354916                            Jawan  2023   15354916   
1  tt15748830                       Jaane Jaan  2023   15748830   
2  tt11663228                           Jailer  2023   11663228   
3  tt14993250  Rocky Aur Rani Kii Prem Kahaani  2023   14993250   
4  tt15732324                            OMG 2  2023   15732324   

                                                tags  
0  [A, high-octane, action, thriller, which, outl...  
1  [A, single, mother, and, her, daughter, who, c...  
2  [A, retired, jailer, goes, on, a, manhunt, to,...  
3  [Flamboyant, Punjabi, Rocky, and, intellectual...  
4  [An, unhappy, civilian, asks, the, court, to, ...

In [28]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))
new_df.head()

movie_id                       movie_name  year  movie_id2  \
0  tt15354916                            Jawan  2023   15354916   
1  tt15748830                       Jaane Jaan  2023   15748830   
2  tt11663228                           Jailer  2023   11663228   
3  tt14993250  Rocky Aur Rani Kii Prem Kahaani  2023   14993250   
4  tt15732324                            OMG 2  2023   15732324   

                                                tags  
0  A high-octane action thriller which outlines t...  
1  A single mother and her daughter who commit a ...  
2  A retired jailer goes on a manhunt to find his...  
3  Flamboyant Punjabi Rocky and intellectual Beng...  
4  An unhappy civilian asks the court to mandate ...

In [29]:
new_df['tags'][0]

'A high-octane action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society. Action,Thriller Atlee ShahRukhKhan,Nayanthara,VijaySethupathi,DeepikaPadukone revenge,chase,suicide,farmer,train,injustice,police,promise,prison,doctor,showdown,society,battle,fight,highoctane,vigilantejustice,fathersonrelationship,sceneduringendcredits,songduringendcredits,finalbattle,dualrole,hijack,womenempowerment,husbandwiferelationship,mothersonrelationship,pregnantwoman,intermission,songanddance,motherdaughterrelationship,actionhero,actionviolence,brotherbrotherrelationship,memoryloss,dogkilled,murderofdog,stabbedwithapen,hangedtodeath,fatherdaughterrelationship,marriage,shotmultipletimes,vigilante,onepersonarmyaction,gunaction,gunbattle,shootout,corruption,suspense,deathofvillain,indestructible,killingmachine'

In [30]:
new_df['tags'] = new_df['tags'].str.replace(',', ' ')

In [31]:
new_df['tags'][0]

'A high-octane action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society. Action Thriller Atlee ShahRukhKhan Nayanthara VijaySethupathi DeepikaPadukone revenge chase suicide farmer train injustice police promise prison doctor showdown society battle fight highoctane vigilantejustice fathersonrelationship sceneduringendcredits songduringendcredits finalbattle dualrole hijack womenempowerment husbandwiferelationship mothersonrelationship pregnantwoman intermission songanddance motherdaughterrelationship actionhero actionviolence brotherbrotherrelationship memoryloss dogkilled murderofdog stabbedwithapen hangedtodeath fatherdaughterrelationship marriage shotmultipletimes vigilante onepersonarmyaction gunaction gunbattle shootout corruption suspense deathofvillain indestructible killingmachine'

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')


In [33]:
vector = cv.fit_transform(new_df['tags']).toarray()

In [34]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
vector.shape

(3976, 5000)

In [36]:
from sklearn.metrics.pairwise import cosine_similarity

In [37]:
similarity = cosine_similarity(vector)

In [38]:
similarity

array([[1.        , 0.04716666, 0.19200614, ..., 0.        , 0.        ,
        0.02178034],
       [0.04716666, 1.        , 0.07018624, ..., 0.        , 0.04376881,
        0.03184649],
       [0.19200614, 0.07018624, 1.        , ..., 0.        , 0.        ,
        0.03241019],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.12598816,
        0.09166985],
       [0.        , 0.04376881, 0.        , ..., 0.12598816, 1.        ,
        0.16169042],
       [0.02178034, 0.03184649, 0.03241019, ..., 0.09166985, 0.16169042,
        1.        ]])

In [39]:
print(similarity)

[[1.         0.04716666 0.19200614 ... 0.         0.         0.02178034]
 [0.04716666 1.         0.07018624 ... 0.         0.04376881 0.03184649]
 [0.19200614 0.07018624 1.         ... 0.         0.         0.03241019]
 ...
 [0.         0.         0.         ... 1.         0.12598816 0.09166985]
 [0.         0.04376881 0.         ... 0.12598816 1.         0.16169042]
 [0.02178034 0.03184649 0.03241019 ... 0.09166985 0.16169042 1.        ]]


In [46]:
def recommend(movie):
    index = new_df[new_df['movie_name'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[0:20]:
        # if i[1] >= 0.3:
            print(new_df.iloc[i[0]].movie_name)      

In [47]:
recommend('Kachche Dhaage')

Kachche Dhaage
Anwar
Pukar
Kurbaan
Zameen
Badal
Tumko Na Bhool Paayenge
Dus
Faraaz
Operation Fryday
Killer - The Hunt
Footpath
Phantom
Karma Strikes
Code Name: Tiranga
Martin
Khakee
Refugee
Khuda Gawah
Yodha


In [44]:
new_df.sample(10)

movie_id       movie_name  year  movie_id2  \
18    tt27542289      Por Thozhil  2023   27542289   
852   tt13364468      Love Hostel  2022   13364468   
1888   tt5637188    Saat Uchakkey  2016    5637188   
3111  tt33058313          Manmayi  2024   33058313   
1233  tt17320574  Acting Ka Bhoot  2023   17320574   
46     tt4430212         Drishyam  2015    4430212   
2782  tt14045080              KTM  2024   14045080   
1396   tt0225961         Hum Dono  1961     225961   
3808  tt30801353   Prem No Padkar  2024   30801353   
1028   tt0206067   Kachche Dhaage  1999     206067   

                                                   tags  
18    A bright but faint-hearted rookie cop has to o...  
852   Set against the pulsating backdrop of rustic N...  
1888  SAAT UCHAKKEY is a comedy caper about 7 petty ...  
3111  Unknown unknown PuluguRamakrishnaReddy NehalGa...  
1233  Two Con Artists with shattered lives and dream...  
46    Desperate measures are taken by a man who trie...  
2782  Karthik seeks love through several attempts. W...  
1396  When an army officer is presumed dead in battl...  
3808  Unknown Drama SatruganGauswami HituKanodia Mam...  
1028  Two stepbrothers who loathe each other have to...

In [61]:
# filtered =new_df[new_df['year'] > 2020]

In [62]:
# filtered.sample(5)

In [63]:
# new_df["movie_id"].duplicated().dropna()

In [64]:
# new_df["movie_id"].duplicated().sum()

In [42]:
pickle.dump(new_df,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))